// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;

// BSOIFull
List BSOIFull(vec Y, mat xi, mat Z_cov, int n_iter, vec beta_k0, vec sigma2_betak0, vec gamma_q0, vec sigma2_gammaq0, double a_delta0, double b_delta0, double alpha, vec beta, vec gamma_cov, double sigma2_delta);
RcppExport SEXP _BSOINN_BSOIFull(SEXP YSEXP, SEXP xiSEXP, SEXP Z_covSEXP, SEXP n_iterSEXP, SEXP beta_k0SEXP, SEXP sigma2_betak0SEXP, SEXP gamma_q0SEXP, SEXP sigma2_gammaq0SEXP, SEXP a_delta0SEXP, SEXP b_delta0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gamma_covSEXP, SEXP sigma2_deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< mat >::type Z_cov(Z_covSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< vec >::type beta_k0(beta_k0SEXP);
    Rcpp::traits::input_parameter< vec >::type sigma2_betak0(sigma2_betak0SEXP);
    Rcpp::traits::input_parameter< vec >::type gamma_q0(gamma_q0SEXP);
    Rcpp::traits::input_parameter< vec >::type sigma2_gammaq0(sigma2_gammaq0SEXP);
    Rcpp::traits::input_parameter< double >::type a_delta0(a_delta0SEXP);
    Rcpp::traits::input_parameter< double >::type b_delta0(b_delta0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< vec >::type gamma_cov(gamma_covSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_delta(sigma2_deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(BSOIFull(Y, xi, Z_cov, n_iter, beta_k0, sigma2_betak0, gamma_q0, sigma2_gammaq0, a_delta0, b_delta0, alpha, beta, gamma_cov, sigma2_delta));
    return rcpp_result_gen;
END_RCPP
}
// BSOIIN
List BSOIIN(vec Y, vec R, mat xi, mat Z_cov, int n_iter, vec beta_k0, vec sigma2_betak0, vec gamma_q0, vec sigma2_gammaq0, double a_delta0, double b_delta0, double alpha, vec beta, vec gamma_cov, double sigma2_delta);
RcppExport SEXP _BSOINN_BSOIIN(SEXP YSEXP, SEXP RSEXP, SEXP xiSEXP, SEXP Z_covSEXP, SEXP n_iterSEXP, SEXP beta_k0SEXP, SEXP sigma2_betak0SEXP, SEXP gamma_q0SEXP, SEXP sigma2_gammaq0SEXP, SEXP a_delta0SEXP, SEXP b_delta0SEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gamma_covSEXP, SEXP sigma2_deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< mat >::type Z_cov(Z_covSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< vec >::type beta_k0(beta_k0SEXP);
    Rcpp::traits::input_parameter< vec >::type sigma2_betak0(sigma2_betak0SEXP);
    Rcpp::traits::input_parameter< vec >::type gamma_q0(gamma_q0SEXP);
    Rcpp::traits::input_parameter< vec >::type sigma2_gammaq0(sigma2_gammaq0SEXP);
    Rcpp::traits::input_parameter< double >::type a_delta0(a_delta0SEXP);
    Rcpp::traits::input_parameter< double >::type b_delta0(b_delta0SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< vec >::type gamma_cov(gamma_covSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_delta(sigma2_deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(BSOIIN(Y, R, xi, Z_cov, n_iter, beta_k0, sigma2_betak0, gamma_q0, sigma2_gammaq0, a_delta0, b_delta0, alpha, beta, gamma_cov, sigma2_delta));
    return rcpp_result_gen;
END_RCPP
}
// BSOINN
List BSOINN(vec Y, vec R, mat xi, mat Z_cov, mat Z_cov_NN, int n_iter, vec beta_k0, vec sigma2_betak0, vec gamma_q0, vec sigma2_gammaq0, double a_delta0, double b_delta0, vec varphi_0, mat sigma_varphi0, double var_ym, double var_varphi, double alpha, vec beta, vec gamma_cov, double sigma2_delta, double alpha_r, vec beta_r, vec gamma_cov_r, double phi);
RcppExport SEXP _BSOINN_BSOINN(SEXP YSEXP, SEXP RSEXP, SEXP xiSEXP, SEXP Z_covSEXP, SEXP Z_cov_NNSEXP, SEXP n_iterSEXP, SEXP beta_k0SEXP, SEXP sigma2_betak0SEXP, SEXP gamma_q0SEXP, SEXP sigma2_gammaq0SEXP, SEXP a_delta0SEXP, SEXP b_delta0SEXP, SEXP varphi_0SEXP, SEXP sigma_varphi0SEXP, SEXP var_ymSEXP, SEXP var_varphiSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gamma_covSEXP, SEXP sigma2_deltaSEXP, SEXP alpha_rSEXP, SEXP beta_rSEXP, SEXP gamma_cov_rSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< mat >::type xi(xiSEXP);
    Rcpp::traits::input_parameter< mat >::type Z_cov(Z_covSEXP);
    Rcpp::traits::input_parameter< mat >::type Z_cov_NN(Z_cov_NNSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< vec >::type beta_k0(beta_k0SEXP);
    Rcpp::traits::input_parameter< vec >::type sigma2_betak0(sigma2_betak0SEXP);
    Rcpp::traits::input_parameter< vec >::type gamma_q0(gamma_q0SEXP);
    Rcpp::traits::input_parameter< vec >::type sigma2_gammaq0(sigma2_gammaq0SEXP);
    Rcpp::traits::input_parameter< double >::type a_delta0(a_delta0SEXP);
    Rcpp::traits::input_parameter< double >::type b_delta0(b_delta0SEXP);
    Rcpp::traits::input_parameter< vec >::type varphi_0(varphi_0SEXP);
    Rcpp::traits::input_parameter< mat >::type sigma_varphi0(sigma_varphi0SEXP);
    Rcpp::traits::input_parameter< double >::type var_ym(var_ymSEXP);
    Rcpp::traits::input_parameter< double >::type var_varphi(var_varphiSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< vec >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< vec >::type gamma_cov(gamma_covSEXP);
    Rcpp::traits::input_parameter< double >::type sigma2_delta(sigma2_deltaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_r(alpha_rSEXP);
    Rcpp::traits::input_parameter< vec >::type beta_r(beta_rSEXP);
    Rcpp::traits::input_parameter< vec >::type gamma_cov_r(gamma_cov_rSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(BSOINN(Y, R, xi, Z_cov, Z_cov_NN, n_iter, beta_k0, sigma2_betak0, gamma_q0, sigma2_gammaq0, a_delta0, b_delta0, varphi_0, sigma_varphi0, var_ym, var_varphi, alpha, beta, gamma_cov, sigma2_delta, alpha_r, beta_r, gamma_cov_r, phi));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BSOINN_BSOIFull", (DL_FUNC) &_BSOINN_BSOIFull, 14},
    {"_BSOINN_BSOIIN", (DL_FUNC) &_BSOINN_BSOIIN, 15},
    {"_BSOINN_BSOINN", (DL_FUNC) &_BSOINN_BSOINN, 24},
    {NULL, NULL, 0}
};

RcppExport void R_init_BSOINN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
