# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BSOIFull <- function(Y, xi, Z_cov, n_iter = 10000, beta_k0 = rep(0,dim(xi)[2]), sigma2_betak0 = rep(100,dim(xi)[2]), gamma_q0 = rep(0.01,dim(Z_cov)[2]), sigma2_gammaq0 = rep(100,dim(Z_cov)[2]), a_delta0 = 9, b_delta0 = 3, alpha = 0.1, beta = rep(0.1,dim(xi)[2]), gamma_cov = rep(0.1,dim(Z_cov)[2]), sigma2_delta=1) {
    .Call('_BSOINN_BSOIFull', PACKAGE = 'BSOINN', Y, xi, Z_cov, n_iter, beta_k0, sigma2_betak0, gamma_q0, sigma2_gammaq0, a_delta0, b_delta0, alpha, beta, gamma_cov, sigma2_delta)
}

BSOIIN <- function(Y, R, xi, Z_cov, n_iter = 10000, beta_k0 = rep(0,dim(xi)[2]), sigma2_betak0 = rep(100,dim(xi)[2]), gamma_q0 = rep(0.01,dim(Z_cov)[2]), sigma2_gammaq0 = rep(100,dim(Z_cov)[2]), a_delta0 = 9, b_delta0 = 3, alpha = 0.1, beta = rep(0.1,dim(xi)[2]), gamma_cov = rep(0.1,dim(Z_cov)[2]), sigma2_delta=1) {
    .Call('_BSOINN_BSOIIN', PACKAGE = 'BSOINN', Y, R, xi, Z_cov, n_iter, beta_k0, sigma2_betak0, gamma_q0, sigma2_gammaq0, a_delta0, b_delta0, alpha, beta, gamma_cov, sigma2_delta)
}

BSOINN <- function(Y, R, xi, Z_cov, Z_cov_NN, n_iter = 10000, beta_k0 = rep(0,dim(xi)[2]), sigma2_betak0 = rep(100,dim(xi)[2]), gamma_q0 = rep(0.01,dim(Z_cov)[2]), sigma2_gammaq0 = rep(100,dim(Z_cov)[2]), a_delta0 = 9, b_delta0 = 3, varphi_0 = c(0,  rep(0,dim(xi)[2]), rep(0,dim(Z_cov_NN)[2]), 0), sigma_varphi0 = diag(2+dim(Z_cov_NN)[2]+dim(xi)[2]), var_ym = 20, var_varphi= 1.5, alpha = 0.1, beta = rep(0.1,dim(xi)[2]), gamma_cov = rep(0.1,dim(Z_cov)[2]), sigma2_delta = 1, alpha_r = 0.1, beta_r = rep(0.1,dim(xi)[2]) , gamma_cov_r = rep(0.1,dim(Z_cov_NN)[2]) , phi=0.1) {
    .Call('_BSOINN_BSOINN', PACKAGE = 'BSOINN', Y, R, xi, Z_cov, Z_cov_NN, n_iter, beta_k0, sigma2_betak0, gamma_q0, sigma2_gammaq0, a_delta0, b_delta0, varphi_0, sigma_varphi0, var_ym, var_varphi, alpha, beta, gamma_cov, sigma2_delta, alpha_r, beta_r, gamma_cov_r, phi)
}

